repos:
-   repo: local
    hooks:
        -   id: phpstan
            name: Run static analysis with PHPStan
            language: system
            entry: "docker-compose run --rm php composer phpstan"
            files: ^.*\.php$
            pass_filenames: false
        -   id: phpunit
            name: Run automated tests
            language: system
            entry: "docker-compose run --rm php composer test"
            files: ^.*\.php$
            pass_filenames: false
        -   id: php-cs-fixer
            name: Enforce coding standards
            language: system
            entry: "docker-compose run --rm php composer cs:fix -- "
            files: ^.*\.php$
