version: "2.2"
services:
    php:
        build: .
        image: local/php-starter
        working_dir: /code
        environment:
            HOME: /code
        volumes:
            - ".:/code:cached"
        user: $DOCKER_COMPOSE_USER

    mariadb:
        image: mariadb
        environment:
            MYSQL_DATABASE: chessable_hr
            MYSQL_ROOT_PASSWORD: example
        ports:
            - 3306:3306
