# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    Example\App\UseCase\:
        resource: '../src/UseCase'
        exclude:
            - '../src/UseCase/**/*{Command,DTO}.php'

    Example\App\Infrastructure\:
        resource: '../src/Infrastructure'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    Example\App\Api\:
        resource: '../src/Api'
        exclude:
            - '../src/Api/Kernel.php'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    Doctrine\DBAL\Connection:
        factory: ['@Example\App\Infrastructure\DbalConnectionFactory', 'test']

    Example\App\Domain\Entity\DepartmentRepository:
        alias: Example\App\Infrastructure\DbalDepartmentRepository
